#!/bin/sh

trap "echo i refuse to interrupt!; exit 1" INT

echo i am executing

echo i am the power

echo i am gonna sleep

sleep 2

echo i am wake

echo goodbye
#!/bin/sh
case $1 in    
	bye)
		echo Fine, bye.
        ;;
	hi|hello)        
		echo Nice to see you.
        ;;    
	what*)        
		echo Whatever.
        ;;
	*)        
		echo 'Huh?'        
		;;
esac
#!/bin/sh
FILE=/tmp/whiletest.$$
echo firstline > $FILE

while tail -10 $FILE | grep -q firstline; do
	echo -n Number of lines in $FILE:' '
	wc -l $FILE | awk '{print $1}'
	echo newline >> $FILE
done

rm -f $FILE
#!/bin/sh
	for str in one two three four; do    
		echo $str
	done
