[package]
name = "ex6"
version = "0.1.0"
authors = ["frind <498296816a@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
